Feature/dotbere 1/dotbere 31 create authentification controller
anggabard/RentApplace-backend pull request #5
Opened 2023-01-13 10:19 UTC by chircancristi

2023-01-13 10:44 UTC, AdiUrs27 approved these changes

2023-01-14 19:20 UTC, anggabard requested changes

2023-01-14 19:20 UTC, anggabard commented on RentApplace/RentApplace.Application/Services/AuthService.cs
> +        private async Task<List<UserRole>> CreateUseRole(User user, List<RoleEnum> roles)
Daca un user poate avea ma multe roluri sau permisiuni cum e posibil sa evolueze aplicatia ma gandeam sa folosim metoda asta pentru a identifica rolurile (https://stackoverflow.com/a/27692680).
Ne va face viata mai usoara sa folosim operatii pe biti pentru identificarea rolurilor decat sa comparam stringuri.

2023-01-14 19:20 UTC, anggabard commented on RentApplace/RentApplace.Application/Services/AuthService.cs
> +        private async Task<List<UserRole>> CreateUseRole(User user, List<RoleEnum> roles)
Pe langa asta, nu va fi nevoie sa inregistram mai multe intrari in tabela user-roles

2023-01-14 19:20 UTC, anggabard commented on RentApplace/RentApplace.Infrastracture/Configurations/RoleConfiguration.cs
> +                    Id = Guid.NewGuid(),
Ce-i asta?

2023-01-15 09:56 UTC, chircancristi commented on RentApplace/RentApplace.API/Middlewares/ExceptionMiddlware.cs
> +                httpContext.Response.StatusCode = exception.StatusCode != null ? (int)exception.StatusCode : (int)HttpStatusCode.BadRequest;
Schimbat

2023-01-15 09:56 UTC, chircancristi commented on RentApplace/RentApplace.Application.UnitTests/Services/AuthentificationServiceTests.cs
> +            Mock<IHashService> hashServiceMock = new Mock<IHashService>(MockBehavior.Strict);
Mutat in constructor, brain fart sounds

2023-01-15 09:56 UTC, chircancristi commented on RentApplace/RentApplace.Application.UnitTests/Services/AuthentificationServiceTests.cs
> +                .Returns(Task.FromResult(validationResult));
Aligned, NICI NU VOIAM BONUS DE CRACIUN OKAY?

2023-01-15 09:57 UTC, chircancristi commented on RentApplace/RentApplace.Application.UnitTests/Services/AuthentificationServiceTests.cs
> +            var exception = await Assert.ThrowsAsync<HttpRequestException>(async () => await AuthService.Register(createUser));
Adaugat comentarii

2023-01-15 09:57 UTC, chircancristi commented on RentApplace/RentApplace.Application.UnitTests/Services/AuthentificationServiceTests.cs
> +        }
Tot trebuie sa verificam ca crapa cand mailu este gresit da mesajul o sa fie diferit

2023-01-15 09:57 UTC, chircancristi commented on RentApplace/RentApplace.Application.UnitTests/Services/AuthentificationServiceTests.cs
> +        public async Task Login_PasswordIncorect_ThrowsUnauthorized()
Same as above

2023-01-15 09:58 UTC, chircancristi commented on RentApplace/RentApplace.Application.UnitTests/Services/AuthentificationServiceTests.cs
> +               );
creat metoda de get AuthService()

2023-01-15 09:59 UTC, chircancristi commented on RentApplace/RentApplace.Application.UnitTests/Services/AuthentificationServiceTests.cs
> +            Assert.Equal(error, exception.Message);
Am scos verificarea de mesaj

2023-01-15 10:07 UTC, chircancristi commented on RentApplace/RentApplace.Application.UnitTests/Services/HashServiceTests.cs
> +            var actual = hashService.VerifyPassword(password, hashPassword, salt);
Schimbat

2023-01-15 10:33 UTC, chircancristi commented on RentApplace/RentApplace.Application.UnitTests/Validators/CreateUserValidatorTests.cs
> +            };
Adaugat functia, good ideea. +5 puncte la marirea de craciun

2023-01-15 10:37 UTC, chircancristi commented on RentApplace/RentApplace.Application/Services/AuthService.cs
> +            }
Schimbat eroare si status code-ul

2023-01-15 10:48 UTC, chircancristi commented on RentApplace/RentApplace.Application/Services/AuthService.cs
> +        private async Task<List<UserRole>> CreateUseRole(User user, List<RoleEnum> roles)
Am modificat in biti

2023-01-15 14:36 UTC, anggabard requested changes

2023-01-15 14:36 UTC, anggabard commented on RentApplace/RentApplace.Application/Services/AuthService.cs
> +                RoleEnum role = (RoleEnum)roleIndex;
Cat mai era sa adaugi si asta in obiectul user de mai jos 🗡️ ?

2023-01-15 14:36 UTC, anggabard commented on RentApplace/RentApplace.Core/Entities/User.cs
> +        public RoleEnum Role { get; set; }
Daca un user va avea mai multe roluri atunci nu putem salva valoarea asta intr-un enum. Putem sa il reprezentam ca un int pentru a-l salva in BD (nu stiu daca asta e cea mai buna optiune) dar ca sa il manevram in cod trebuie sa folosim alt timp de data

2023-01-15 15:27 UTC, chircancristi commented on RentApplace/RentApplace.Application/Services/AuthService.cs
> +                RoleEnum role = (RoleEnum)roleIndex;
il folosesc in 2 locuril, lasal acolo in variabila ca e bine asa

2023-01-16 07:09 UTC, anggabard commented on RentApplace/RentApplace.Application/Services/AuthService.cs
> +                RoleEnum role = (RoleEnum)roleIndex;
`var user = new User
                {
                    Email = roleIndex.ToString(),
                    Role = (RoleEnum)roleIndex
                };`
si dupa
`result.Add(new TokenResponse { Token = jWTTokenResponse, Role = user.Role.ToString() });`
te rog merci pwp :3

2023-01-16 07:44 UTC, anggabard approved these changes

2023-01-16 07:47 UTC, merged